trying to fix convert_gptq_v2_to_v1_format_module
    module.qzeros.data[:, range(0, module.qzeros.data.shape[1], 3)] -= (
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed